In [5]:
import pandas as pd

In [7]:
df = pd.read_excel(r"C:\Users\vaide\Downloads\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [9]:
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [25]:
print(df.columns)

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact'],
      dtype='object')

In [168]:
df = df.drop(columns="Not_Useful_Column", errors='ignore')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [11]:
df["Last_Name"] = df["Last_Name"].str.strip("abc./_")
df["Last_Name"]

C:\Users\vaide\AppData\Local\Temp\ipykernel_34372\1723015199.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last_Name"] = df["Last_Name"].str.strip("abc./_")

0        Baggins
1          Nadir
2          White
3        Schrute
4           Snow
5        Swanson
6         Winger
7         Holmes
8            NaN
9         Parker
10        Gamgee
11        Potter
12        Draper
13         Knope
14    Flenderson
15       Weasley
16         Scott
17          Kent
18        Braton
19     Skywalker
Name: Last_Name, dtype: object

In [13]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [15]:
df["Phone_Number"] = df["Phone_Number"].str.replace('[^a-zA-Z0-9]', '', regex=True)
df["Phone_Number"]

C:\Users\vaide\AppData\Local\Temp\ipykernel_34372\688638922.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Phone_Number"] = df["Phone_Number"].str.replace('[^a-zA-Z0-9]', '', regex=True)

0     1235455421
1     1236439775
2            NaN
3     1235432345
4     8766783469
5     3047622467
6            NaN
7     8766783469
8             Na
9     1235455421
10           NaN
11           NaN
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17           NaN
18            Na
19    8766783469
Name: Phone_Number, dtype: object

In [172]:
# Clean 'N/a' or missing values
df["Address"] = df["Address"].replace("N/a", "").fillna("")

# Split the address into columns based on commas
df_split = df["Address"].str.split(",", expand=True)

# Rename the columns for clarity
df_split.columns = ["Street", "City", "State"]

df.drop(["Street", "City", "State"], axis=1, errors="ignore")

# Add the split columns back to the original DataFrame, but only if they are not already present
df = pd.concat([df.drop(["Street", "City", "State"], axis=1, errors="ignore"), df_split], axis=1)

# Display the updated DataFrame
print(df)

    CustomerID First_Name    Last_Name  Phone_Number  \
0         1001      Frodo      Baggins  123-545-5421
1         1002       Abed        Nadir  123/643/9775
2         1003     Walter       /White    7066950392
3         1004     Dwight      Schrute  123-543-2345
4         1005        Jon         Snow  876|678|3469
5         1006        Ron      Swanson  304-762-2467
6         1007       Jeff       Winger           NaN
7         1008   Sherlock       Holmes  876|678|3469
8         1009    Gandalf          NaN           N/a
9         1010      Peter       Parker  123-545-5421
10        1011    Samwise       Gamgee           NaN
11        1012      Harry    ...Potter    7066950392
12        1013        Don       Draper  123-543-2345
13        1014     Leslie        Knope  876|678|3469
14        1015       Toby  Flenderson_  304-762-2467
15        1016        Ron      Weasley  123-545-5421
16        1017   Michael         Scott  123/643/9775
17        1018      Clark         Kent    7066950392
18        1019      Creed       Braton           N/a
19        1020     Anakin    Skywalker  876|678|3469

                                  Address Paying Customer Do_Not_Contact  \
0                   123 Shire Lane, Shire             Yes             No
1                     93 West Main Street              No            Yes
2                      298 Drugs Driveway               N            NaN
3   980 Paper Avenue, Pennsylvania, 18503             Yes              Y
4                        123 Dragons Road               Y             No
5                        768 City Parkway             Yes            Yes
6                       1209 South Street              No             No
7                           98 Clue Drive               N             No
8                        123 Middle Earth             Yes            NaN
9              25th Main Street, New York             Yes             No
10                  612 Shire Lane, Shire             Yes             No
11                   2394 Hogwarts Avenue               Y            NaN
12                       2039 Main Street             Yes              N
13                       343 City Parkway             Yes             No
14                          214 HR Avenue               N             No
15                   2395 Hogwarts Avenue              No              N
16         121 Paper Avenue, Pennsylvania             Yes             No
17                        3498 Super Lane               Y            NaN
18                                                    N/a            Yes
19            910 Tatooine Road, Tatooine             Yes              N

                  Street           City   State
0         123 Shire Lane          Shire    None
1    93 West Main Street           None    None
2     298 Drugs Driveway           None    None
3       980 Paper Avenue   Pennsylvania   18503
4       123 Dragons Road           None    None
5       768 City Parkway           None    None
6      1209 South Street           None    None
7          98 Clue Drive           None    None
8       123 Middle Earth           None    None
9       25th Main Street       New York    None
10        612 Shire Lane          Shire    None
11  2394 Hogwarts Avenue           None    None
12      2039 Main Street           None    None
13      343 City Parkway           None    None
14         214 HR Avenue           None    None
15  2395 Hogwarts Avenue           None    None
16      121 Paper Avenue   Pennsylvania    None
17       3498 Super Lane           None    None
18                                 None    None
19     910 Tatooine Road       Tatooine    None

In [112]:
# Drop the Address column
df = df.drop("Address", axis=1)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,State
0,1001,Frodo,Baggins,1235455421,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,1236439775,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,NaN,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,NaN,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,NaN,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,NaN,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,,None,None
19,1020,Anakin,Skywalker,8766783469,Yes,N,910 Tatooine Road,Tatooine,None

In [202]:
df["Paying Customer"] = df["Paying Customer"].str.replace('Yes', 'Y')
df["Paying Customer"] = df["Paying Customer"].str.replace('No', 'N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,City,State
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,No,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,98 Clue Drive,,
8,1009,Gandalf,,N/a,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,No,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,No,612 Shire Lane,Shire,
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,No,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Y,No,343 City Parkway,,
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,No,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Y,No,910 Tatooine Road,Tatooine,

In [176]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes', 'Y')
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No', 'N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,City,State
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,N,Y,93 West Main Street,None,None
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a,,N/a,Y,,None,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [204]:
df = df.replace('N/a', '')
df = df.replace('NaN', '')
df = df.fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,City,State
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,No,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,No,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,No,612 Shire Lane,Shire,
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,No,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Y,No,343 City Parkway,,
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,No,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Y,No,910 Tatooine Road,Tatooine,

In [208]:
# Drop rows where 'Do_Not_Contact' is 'Yes'
df = df[df['Do_Not_Contact'] != 'Yes']

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,City,State
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,No,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,No,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,No,612 Shire Lane,Shire,
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,No,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Y,No,343 City Parkway,,
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,No,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Y,No,910 Tatooine Road,Tatooine,

In [210]:
# Drop rows where 'Phone_Number' is null (NaN)
df = df.dropna(subset=['Phone_Number'])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,City,State
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,No,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,No,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,No,612 Shire Lane,Shire,
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,No,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Y,No,343 City Parkway,,
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,No,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Y,No,910 Tatooine Road,Tatooine,

In [214]:
df["Phone_Number"]

0     123-545-5421
2       7066950392
4     876|678|3469
6
7     876|678|3469
8
9     123-545-5421
10
11      7066950392
12    123-543-2345
13    876|678|3469
14    304-762-2467
15    123-545-5421
16    123/643/9775
17      7066950392
19    876|678|3469
Name: Phone_Number, dtype: object

In [19]:
# Convert all values in 'Phone_Number' to strings, replacing NaN with empty strings
df['Phone_Number'] = df['Phone_Number'].astype(str).fillna('')

# Remove all non-numeric characters and standardize the format
df['Phone_Number'] = (
    df['Phone_Number']
    .str.replace(r'[^0-9]', '', regex=True)  # Remove non-numeric characters
    .str.slice(start=0, stop=10)            # Take the first 10 digits (if valid)
    .apply(lambda x: f"{x[:3]}-{x[3:6]}-{x[6:]}" if len(x) == 10 else '')  # Format or set empty
)
df

C:\Users\vaide\AppData\Local\Temp\ipykernel_34372\2916343505.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number'] = df['Phone_Number'].astype(str).fillna('')
C:\Users\vaide\AppData\Local\Temp\ipykernel_34372\2916343505.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number'] = (

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True